# Generated by Django 4.1.5 on 2023-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_delete_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defult.png', upload_to='profile/'),
        ),
    ]
